// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjdlkninwrlzjmfeefej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZGxrbmlud3JsemptZmVlZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzgyNDcsImV4cCI6MjA2NTMxNDI0N30.v1QIEbg1G_3IfkYFaJBI7BKDOgaYT2FQ6dI8sZ-kdV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);